#[derive(PartialEq)]
#[derive(Debug)]
pub enum Token {
    // Keywords
    If,
    Else,
    While,
    For,
    Struct,
    Break,
    Continue,
    Return,
    New,
    True,
    False,
    // Identifiers
    Identifier(String),
    // Literal
    IntLiteral(String),
    FloatLiteral(String),
    StringLiteral(String),
    NullLiteral,
    // Operators
    Plus,
    Minus,
    Multiply,
    Divide,
    Modulo,
    Or,
    And,
    Not,
    LessThan,
    GreaterThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    Equal,
    NotEqual,
    Assignment,
    Increment,
    Decrement,
    Hash,
    LeftShift,
    RightShift,
    // Delimeter
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Dot,
    Semicolon,
    // Special Tokens
    Illegal,
    Eof,
}